Vagrant.configure("2") do |c|
  c.vm.define 'centos-64-x64' do |v|
    v.vm.hostname = 'centos-64-x64'
    v.vm.box = 'centos-64-x64-vbox4210-nocm'
    v.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
    v.vm.base_mac = '080027EE3253'
    v.vm.network :private_network, ip: "10.255.156.78", :netmask => "255.255.0.0"
  end
  c.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
